# Generated by Django 6.0.3 on 2026-06-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='bvn_or_nin',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='document_number',
            field=models.CharField(default='default', help_text='Document ID number (BVN, NIN, License, or Passport number)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('bvn', 'BVN'), ('nin', 'NIN'), ('drivers_license', "Driver's License"), ('passport', 'Passport')], default='nin', max_length=20),
        ),
    ]
