# Generated by Django 6.0.3 on 2026-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_remove_kycverification_bvn_or_nin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='selfie_url',
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_number',
            field=models.CharField(help_text='Document ID number (NIN, License, or Passport number)', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('nin', 'NIN'), ('drivers_license', "Driver's License"), ('passport', 'Passport')], default='nin', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
    ]
