# Generated by Django 6.0.3 on 2026-06-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_remove_kycverification_selfie_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='face_match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='liveness_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='prembly_id_photo',
            field=models.TextField(blank=True, help_text='Base64 photo from Prembly BVN/NIN response'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='prembly_verified_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='selfie_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='selfie_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the user selfie for face matching', max_length=500),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_url',
            field=models.URLField(blank=True, help_text='URL from Cloudinary/S3 containing the ID document image', max_length=500),
        ),
    ]
