# Generated by Django 6.0.3 on 2026-06-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_kycverification_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='document_number',
            field=models.CharField(help_text='Document ID number (NIN, BVN, or License number)', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('nin', 'NIN'), ('bvn', 'BVN'), ('drivers_license', "Driver's License")], default='nin', max_length=20),
        ),
    ]
