# Generated by Django 6.0.3 on 2026-07-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_alter_kycverification_document_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='face_match_confidence',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='liveness_confidence',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='needs_manual_review',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='prembly_id_photo',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='prembly_verified_name',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='selfie_attempts',
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_number',
            field=models.CharField(help_text="Document ID number (NIN, Voter's Card, or License number)", max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('nin', 'NIN'), ('voters_card', "Voter's Card"), ('drivers_license', "Driver's License")], default='nin', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('submitted', 'Submitted'), ('resubmission', 'Resubmission'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
    ]
