# Generated by Django 6.0.3 on 2026-07-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_remove_kycverification_face_match_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='document_number',
            field=models.CharField(help_text="Document ID number (NIN, Voter's Card, License number, or Passport number)", max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('nin', 'NIN'), ('voters_card', "Voter's Card"), ('drivers_license', "Driver's License"), ('international_passport', 'International Passport')], default='nin', max_length=50),
        ),
    ]
