# Generated by Django 6.0.3 on 2026-07-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_alter_kycverification_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('submitted', 'Submitted'), ('resubmission', 'Resubmission'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
    ]
