# Generated by Django 6.0.3 on 2026-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt', 'Tether'), ('usdc', 'USD Coin'), ('sol', 'Solana'), ('bnb', 'Binance Coin')], max_length=10, unique=True)),
                ('rate_ngn', models.DecimalField(decimal_places=2, help_text='Raw market rate in NGN from CoinGecko', max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cached Rate',
                'verbose_name_plural': 'Cached Rates',
                'db_table': 'cached_rates',
            },
        ),
    ]
