# Generated by Django 6.0.3 on 2026-06-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedrate',
            name='rate_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Raw market rate in USD from CoinGecko', max_digits=20, null=True),
        ),
    ]
