# Generated by Django 6.0.3 on 2026-06-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FFFFFF', max_length=50)),
                ('bg', models.CharField(default='linear-gradient(135deg, #1a1a1a, #000000)', max_length=255)),
                ('denominations', models.JSONField(default=list)),
                ('rates', models.JSONField(default=dict)),
                ('rate_per_dollar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(max_length=50)),
                ('popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'db_table': 'gift_cards',
            },
        ),
    ]
