# Generated by Django 6.0.3 on 2026-06-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ngn_usd_buy_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='If greater than 0, this explicit NGN/USD rate is used to calculate user payouts directly, ignoring the margin percentage.', max_digits=10),
        ),
    ]
