# Generated by Django 6.0.3 on 2026-07-14 15:34

import django.db.models.deletion
import rates.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_systemsettings_ngn_usd_buy_rate'),
        ('wallets', '0003_alter_depositaddress_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rejection Reason',
                'verbose_name_plural': 'Rejection Reasons',
                'db_table': 'giftcard_rejection_reasons',
                'ordering': ['label'],
            },
        ),
        migrations.AlterField(
            model_name='cachedrate',
            name='asset',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt', 'Tether'), ('usdc', 'USD Coin'), ('bnb', 'Binance Coin')], max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='e.g. Amazon', max_length=100)),
                ('country_code', models.CharField(help_text='e.g. US', max_length=10)),
                ('currency_symbol', models.CharField(help_text='e.g. $', max_length=5)),
                ('denomination', models.DecimalField(decimal_places=2, help_text='Face value of the card in its native currency', max_digits=12)),
                ('rate_applied', models.DecimalField(decimal_places=2, help_text='NGN rate per unit at time of submission', max_digits=12)),
                ('ngn_payout', models.DecimalField(decimal_places=2, help_text='Expected NGN payout = denomination × rate', max_digits=20)),
                ('image_url', models.URLField(help_text='Cloudinary secure_url of the uploaded gift card image', max_length=1000)),
                ('card_code', models.CharField(blank=True, help_text='Optional card code typed by the user', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(default=rates.models.generate_gc_reference, max_length=10, unique=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_giftcard_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftcard_transactions', to='wallets.ngnwallet')),
                ('rejection_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='rates.rejectionreason')),
            ],
            options={
                'verbose_name': 'Gift Card Transaction',
                'verbose_name_plural': 'Gift Card Transactions',
                'db_table': 'giftcard_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='giftcard_tr_user_id_b40c3b_idx'), models.Index(fields=['status', '-created_at'], name='giftcard_tr_status_005324_idx')],
            },
        ),
    ]
