# Generated by Django 6.0.3 on 2026-07-14 15:40

from django.db import migrations

DEFAULT_REASONS = [
    {
        "code": "already_used",
        "label": "Card Already Used",
        "description": "This gift card has already been redeemed or has a zero balance.",
    },
    {
        "code": "image_blurry",
        "label": "Image Too Blurry / Unreadable",
        "description": "The card image is not clear enough to verify the code or denomination.",
    },
    {
        "code": "wrong_denomination",
        "label": "Invalid Denomination",
        "description": "The card value does not match the denomination you stated.",
    },
    {
        "code": "unsupported_country",
        "label": "Card Not Supported in Selected Country",
        "description": "This brand/country combination is not currently supported.",
    },
    {
        "code": "expired",
        "label": "Expired Gift Card",
        "description": "The gift card has passed its expiry date.",
    },
    {
        "code": "duplicate",
        "label": "Duplicate Submission",
        "description": "This card has already been submitted for review.",
    },
]


def seed_reasons(apps, schema_editor):
    RejectionReason = apps.get_model("rates", "RejectionReason")
    for r in DEFAULT_REASONS:
        RejectionReason.objects.get_or_create(code=r["code"], defaults={
            "label": r["label"],
            "description": r["description"],
            "is_active": True,
        })


def unseed_reasons(apps, schema_editor):
    RejectionReason = apps.get_model("rates", "RejectionReason")
    codes = [r["code"] for r in DEFAULT_REASONS]
    RejectionReason.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_add_giftcard_transaction_and_rejection_reason'),
    ]

    operations = [
        migrations.RunPython(seed_reasons, unseed_reasons),
    ]
