# Generated by Django 6.0.3 on 2026-07-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_seed_default_rejection_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='rate_multiplier',
            field=models.DecimalField(decimal_places=4, default=0.9, help_text='Multiplier applied to NGN/USD buy rate (e.g. 0.9000 for 90%)', max_digits=6),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='use_auto_rate',
            field=models.BooleanField(default=True, help_text='Automatically calculate rate from NGN/USD buy rate'),
        ),
    ]
