# Generated by Django 6.0.3 on 2026-07-14 17:23

from django.db import migrations
from decimal import Decimal

DEFAULT_GIFTCARDS = [
    # Amazon
    {
        "brand": "Amazon",
        "category": "E-Commerce",
        "color": "#FF9900",
        "bg": "linear-gradient(135deg,#1a0800,#3d1f00)",
        "denominations": ["25", "50", "100", "200"],
        "rates": {},
        "rate_per_dollar": Decimal("0.00"),
        "country": "US",
        "popular": True,
        "use_auto_rate": True,
        "rate_multiplier": Decimal("0.9000"), # 90% of base rate
    },
    {
        "brand": "Amazon",
        "category": "E-Commerce",
        "color": "#FF9900",
        "bg": "linear-gradient(135deg,#1a0800,#3d1f00)",
        "denominations": ["25", "50", "100"],
        "rates": {},
        "rate_per_dollar": Decimal("0.00"),
        "country": "UK",
        "popular": False,
        "use_auto_rate": True,
        "rate_multiplier": Decimal("0.8800"),
    },
    # iTunes
    {
        "brand": "iTunes",
        "category": "Music & Software",
        "color": "#FC3C44",
        "bg": "linear-gradient(135deg,#1a001a,#330020)",
        "denominations": ["15", "25", "50", "100"],
        "rates": {},
        "rate_per_dollar": Decimal("0.00"),
        "country": "US",
        "popular": True,
        "use_auto_rate": True,
        "rate_multiplier": Decimal("0.8500"),
    },
    {
        "brand": "iTunes",
        "category": "Music & Software",
        "color": "#FC3C44",
        "bg": "linear-gradient(135deg,#1a001a,#330020)",
        "denominations": ["15", "25", "50"],
        "rates": {},
        "rate_per_dollar": Decimal("0.00"),
        "country": "UK",
        "popular": False,
        "use_auto_rate": True,
        "rate_multiplier": Decimal("0.8300"),
    },
    # Steam
    {
        "brand": "Steam",
        "category": "Gaming",
        "color": "#66C0F4",
        "bg": "linear-gradient(135deg,#00101a,#001f33)",
        "denominations": ["10", "20", "50", "100"],
        "rates": {},
        "rate_per_dollar": Decimal("0.00"),
        "country": "US",
        "popular": True,
        "use_auto_rate": True,
        "rate_multiplier": Decimal("0.8500"),
    },
    # Google Play
    {
        "brand": "Google Play",
        "category": "Mobile Apps & Gaming",
        "color": "#0ECB81",
        "bg": "linear-gradient(135deg,#001a08,#003318)",
        "denominations": ["10", "25", "50", "100"],
        "rates": {},
        "rate_per_dollar": Decimal("0.00"),
        "country": "US",
        "popular": True,
        "use_auto_rate": True,
        "rate_multiplier": Decimal("0.8700"),
    },
    # Netflix
    {
        "brand": "Netflix",
        "category": "Streaming & Entertainment",
        "color": "#E50914",
        "bg": "linear-gradient(135deg,#1a0000,#330000)",
        "denominations": ["15", "30", "60", "100"],
        "rates": {},
        "rate_per_dollar": Decimal("0.00"),
        "country": "US",
        "popular": False,
        "use_auto_rate": True,
        "rate_multiplier": Decimal("0.8200"),
    },
    # Xbox
    {
        "brand": "Xbox",
        "category": "Gaming",
        "color": "#107C10",
        "bg": "linear-gradient(135deg,#001a00,#003300)",
        "denominations": ["10", "25", "50", "100"],
        "rates": {},
        "rate_per_dollar": Decimal("0.00"),
        "country": "US",
        "popular": False,
        "use_auto_rate": True,
        "rate_multiplier": Decimal("0.8000"),
    },
    # Visa
    {
        "brand": "Visa",
        "category": "Prepaid Debit",
        "color": "#6B8AFE",
        "bg": "linear-gradient(135deg,#000818,#001433)",
        "denominations": ["50", "100", "200", "500"],
        "rates": {},
        "rate_per_dollar": Decimal("0.00"),
        "country": "US",
        "popular": False,
        "use_auto_rate": True,
        "rate_multiplier": Decimal("0.8800"),
    },
    # Razer Gold
    {
        "brand": "Razer Gold",
        "category": "Gaming Credits",
        "color": "#44D62C",
        "bg": "linear-gradient(135deg,#001a00,#002800)",
        "denominations": ["5", "10", "25", "50"],
        "rates": {},
        "rate_per_dollar": Decimal("0.00"),
        "country": "US",
        "popular": True,
        "use_auto_rate": True,
        "rate_multiplier": Decimal("0.8600"),
    },
]


def seed_giftcards(apps, schema_editor):
    GiftCard = apps.get_model("rates", "GiftCard")
    for g in DEFAULT_GIFTCARDS:
        GiftCard.objects.get_or_create(
            brand=g["brand"],
            country=g["country"],
            defaults={
                "category": g["category"],
                "color": g["color"],
                "bg": g["bg"],
                "denominations": g["denominations"],
                "rates": g["rates"],
                "rate_per_dollar": g["rate_per_dollar"],
                "popular": g["popular"],
                "use_auto_rate": g["use_auto_rate"],
                "rate_multiplier": g["rate_multiplier"],
            }
        )


def unseed_giftcards(apps, schema_editor):
    GiftCard = apps.get_model("rates", "GiftCard")
    for g in DEFAULT_GIFTCARDS:
        GiftCard.objects.filter(brand=g["brand"], country=g["country"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0008_add_giftcard_auto_rate_fields'),
    ]

    operations = [
        migrations.RunPython(seed_giftcards, unseed_giftcards),
    ]
