# Generated by Django 6.0.3 on 2026-06-04 14:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt', 'Tether'), ('usdc', 'USD Coin'), ('sol', 'Solana'), ('bnb', 'Binance Coin')], max_length=10)),
                ('network', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('erc20', 'ERC-20'), ('trc20', 'TRC-20'), ('bep20', 'BEP-20'), ('solana', 'Solana')], max_length=20)),
                ('crypto_amount', models.DecimalField(decimal_places=8, help_text='Amount of crypto deposited', max_digits=20)),
                ('rate_applied', models.DecimalField(decimal_places=2, help_text='User rate (NGN) at the time of conversion', max_digits=20)),
                ('margin_applied', models.DecimalField(decimal_places=2, help_text='Margin percentage applied at conversion', max_digits=5)),
                ('ngn_amount', models.DecimalField(decimal_places=2, help_text='Final NGN amount credited to wallet', max_digits=20)),
                ('quidax_reference', models.CharField(help_text='Quidax transaction ID for idempotency', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('converted', 'Converted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='wallets.ngnwallet')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'db_table': 'deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of NGN to withdraw', max_digits=20)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Any withdrawal fee applied', max_digits=10)),
                ('paystack_reference', models.CharField(default=uuid.uuid4, help_text='Unique reference for Paystack', max_length=255, unique=True)),
                ('paystack_transfer_code', models.CharField(blank=True, help_text='Transfer code from Paystack', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallets.bankaccount')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.ngnwallet')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in NGN', max_digits=20)),
                ('reference', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.deposit')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.ngnwallet')),
                ('related_withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.withdrawal')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
