# Generated by Django 6.0.3 on 2026-06-06 20:34

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default=transactions.models.generate_transaction_id, max_length=10, unique=True),
        ),
    ]
