# Generated by Django 6.0.3 on 2026-06-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='ngn_usd_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NGN/USD rate at time of conversion (user-friendly rate shown on Live Rates)', max_digits=10, null=True),
        ),
    ]
