# Generated by Django 6.0.3 on 2026-07-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_add_ngn_usd_rate_to_deposit'),
        ('wallets', '0002_depositaddress_derivation_index_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['wallet', '-created_at'], name='deposits_wallet__127754_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', '-created_at'], name='transaction_wallet__91699c_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['wallet', '-created_at'], name='withdrawals_wallet__b5733c_idx'),
        ),
    ]
