# Generated by Django 6.0.3 on 2026-07-14 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0009_seed_default_giftcards'),
        ('transactions', '0005_rename_quidax_reference_to_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_giftcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rates.giftcardtransaction'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='asset',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt', 'Tether'), ('usdc', 'USD Coin'), ('bnb', 'Binance Coin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='network',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin'), ('erc20', 'ERC-20'), ('bep20', 'BEP-20')], max_length=20),
        ),
    ]
