# Generated by Django 6.0.3 on 2026-05-30 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
