# Generated by Django 6.0.3 on 2026-06-15 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0006_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinUpdateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_update_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PIN Update Token',
                'verbose_name_plural': 'PIN Update Tokens',
                'db_table': 'pin_update_tokens',
            },
        ),
    ]
