# Generated by Django 6.0.3 on 2026-07-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0007_pinupdatetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frozen_at',
            field=models.DateTimeField(blank=True, help_text='When the account was frozen', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='frozen_reason',
            field=models.CharField(blank=True, default='', help_text='Admin reason for freezing the account', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='Freeze account to block withdrawals'),
        ),
    ]
