# Generated by Django 6.0.3 on 2026-06-04 14:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(help_text='Paystack bank code', max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(help_text='Resolved account name from Paystack', max_length=255)),
                ('paystack_recipient_code', models.CharField(blank=True, help_text='Paystack transfer recipient code', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='NGNWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current NGN balance', max_digits=15)),
                ('quidax_user_id', models.CharField(blank=True, help_text='Quidax sub-account ID for this user', max_length=255)),
                ('transaction_pin_hash', models.CharField(blank=True, help_text='Hashed 4-digit transaction PIN', max_length=128)),
                ('pin_is_set', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ngn_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NGN Wallet',
                'verbose_name_plural': 'NGN Wallets',
                'db_table': 'ngn_wallets',
            },
        ),
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt', 'Tether'), ('usdc', 'USD Coin'), ('sol', 'Solana'), ('bnb', 'Binance Coin')], max_length=10)),
                ('network', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('erc20', 'ERC-20'), ('trc20', 'TRC-20'), ('bep20', 'BEP-20'), ('solana', 'Solana')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_addresses', to='wallets.ngnwallet')),
            ],
            options={
                'verbose_name': 'Deposit Address',
                'verbose_name_plural': 'Deposit Addresses',
                'db_table': 'deposit_addresses',
                'unique_together': {('wallet', 'asset', 'network')},
            },
        ),
    ]
