# Generated by Django 6.0.3 on 2026-06-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaddress',
            name='derivation_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositaddress',
            name='tatum_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
