# Generated by Django 6.0.3 on 2026-07-06 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_depositaddress_derivation_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaddress',
            name='asset',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt', 'Tether'), ('usdc', 'USD Coin'), ('bnb', 'Binance Coin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='depositaddress',
            name='network',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin'), ('erc20', 'ERC-20'), ('bep20', 'BEP-20')], max_length=20),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweep_pin_hash', models.CharField(blank=True, max_length=128)),
                ('pin_is_set', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='SweepRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('erc20', 'ERC-20'), ('bep20', 'BEP-20')], max_length=20)),
                ('asset', models.CharField(choices=[('btc', 'BTC'), ('eth', 'ETH'), ('usdt', 'USDT'), ('usdc', 'USDC'), ('bnb', 'BNB')], max_length=10)),
                ('addresses_swept', models.JSONField(default=list, help_text='List of sub-wallet addresses included')),
                ('total_crypto_amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('gas_cost_crypto', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('destination_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sweep_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sweep Request',
                'verbose_name_plural': 'Sweep Requests',
                'db_table': 'sweep_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
